### ISSUE TITLE
Message Unresolved Import for CP437_CONTROL with Rust Analyzer

### ISSUE THREAD

**Issue by Christoph-AK** [nabijaczleweli/codepage-437#1]
Hi there, firstly thanks alot for this library, really helps me a ton parsing output from legacy applications.

When using the CP437_CONTROL import, rust analyzer sometimes marks it as missing import. Compilation works fine afterwards.

Is this an error in rust analyzer, or is some import in this crate malformed?

![grafik](https://user-images.githubusercontent.com/72923608/158357925-d1a304d4-307a-4748-a4fb-f21224749c1f.png)

(Running Windows, Rust 1.59.0 with 2021 Edition, Rust Analyzer v0.2.975)

**Comment by nabijaczleweli** [comment]
I don't really see how this is in scope. It's generated by the build script, it works. If third-party software analysing this chokes on it, then *it*'s broken, not this.
